Controllers/LibrosController.cs
using Microsoft.AspNetCore.Mvc;
using SegundaPracticaMVC.Repositories;
using SegundaPracticaMVC.Filters;
using PruebaExamen.Repositories;
using SegundaPracticaMVC.Models;
using SegundaPracticaMVC.Extensions;

namespace SegundaPracticaMVC.Controllers
{
    public class LibrosController : Controller
    {
        private RepositoryLibros repo;
        public LibrosController(RepositoryLibros repo)
        {
            this.repo = repo;
        }

        [AuthorizeUsuarios]
        public IActionResult PerfilUsuario()
        {
            return View();
        }
        [AuthorizeUsuarios]
        public async Task<IActionResult> Index()
        {
            List<Libro> libros = await this.repo.GetLibrosAsync();
            return View(libros);
        }


        [AuthorizeUsuarios]
        public async Task<IActionResult> LibrosGenero(int idgenero)
        {
            List<Libro> peliculasGenero = await this.repo.LibrosGeneroAsync(idgenero);
            return View(peliculasGenero);
        }

        [AuthorizeUsuarios]
        public async Task<IActionResult> DetallesLibro(int id)
        {
            Libro libro = await this.repo.FindLibroAsync(id);
            return View(libro);
        }
        public IActionResult GuardarLibroCarrito(int idLibro)
        {
            int cantidadCarrito = HttpContext.Session.GetObject<int>("CANTIDADCARRITO");
            if (idLibro != null)
            {
                List<int> carrito;
                if (HttpContext.Session.GetObject<List<int>>("CARRITO") == null)
                {
                    carrito = new List<int>();
                }
                else
                {
                    carrito = HttpContext.Session.GetObject<List<int>>("CARRITO");
                }
                carrito.Add(idLibro);
                HttpContext.Session.SetObject("CARRITO", carrito);
                HttpContext.Session.SetObject("CANTIDADCARRITO", carrito.Count);
            }

                return RedirectToAction("DetallesLibro", new { id = idLibro });

        }

        public IActionResult Carrito(int? idLibroEliminar)
        {
            //LE PASAMOS EL CARRITO
            List<int> carrito = HttpContext.Session.GetObject<List<int>>("CARRITO");
            int cantidadCarrito = carrito.Count;
            //TIENES QUE CREAR PARA AÑADIR DATOS AL CARRITO
            if (carrito == null)
            {
                return View();
            }
            else
            {
                if (idLibroEliminar != null)
                {
                    carrito.Remove(idLibroEliminar.Value);
                    cantidadCarrito--;
                    HttpContext.Session.SetObject("CARRITO", carrito);
                    HttpContext.Session.SetObject("CANTIDADCARRITO", cantidadCarrito);
                }
                List<Libro> libros = this.repo.GetLibrosCarrito(carrito);
                return View(libros);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Comprar(List<int> libros, int iduser)
        {
            int idpedido = await repo.GetUltimoPedido();
            int idfactura = await repo.GetUltimaFactura()+1;
            for (int i = 0; i < libros.Count; i++)
            {
                int libro = libros[i];

                idpedido++;
                Pedido nuevoPedido = new Pedido()
                {
                    IdPedido = idpedido,
                    IdFactura = idfactura,
                    IdLibro = libro,
                    FechaCompra = DateTime.Now,
                    IdUsuario = iduser,
                    Cantidad = 1
                };

                await repo.Comprar(nuevoPedido);

            }
            HttpContext.Session.Remove("CARRITO");
            HttpContext.Session.Remove("CANTIDADCARRITO");

            return RedirectToAction("Index");
        }


        [AuthorizeUsuarios]
        public async Task<IActionResult> PedidosUsuario(int id)
        {
            List<ViewPedidos> pedidos = await this.repo.GetPedidosUsuario(id);
            return View(pedidos);
        }



    }
}

Controllers/ManagedController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using SegundaPracticaMVC.Models.PruebaExamen.Models;
using SegundaPracticaMVC.Repositories;
using System.Security.Claims;

namespace SegundaPracticaMVC.Controllers
{
    public class ManagedController : Controller
    {
        private RepositoryUsuarios repo;

        public ManagedController(RepositoryUsuarios repo)
        {
            this.repo = repo;
        }

        public IActionResult Login()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Login(string email, string password)
        {
            Usuario usuario = await this.repo.GetUserByEmailPasswordAsync(email, password);
            if (usuario != null)
            {
                // Seguridad
                ClaimsIdentity identity =
                    new ClaimsIdentity(
                        CookieAuthenticationDefaults.AuthenticationScheme,
                        ClaimTypes.Name, ClaimTypes.Role);

               
                Claim claimName = new Claim(ClaimTypes.Name, usuario.Nombre);
                identity.AddClaim(claimName);

                Claim claimId = new Claim(ClaimTypes.NameIdentifier, usuario.IdUsuario.ToString());
                identity.AddClaim(claimId);

                Claim claimEmail = new Claim(ClaimTypes.Role, usuario.Email);
                identity.AddClaim(claimEmail);

                Claim claimIDforma2 = new Claim("id", usuario.IdUsuario.ToString());
                identity.AddClaim(claimIDforma2);

                Claim claimEmail2 = new Claim("Email", usuario.Email.ToString());
                identity.AddClaim(claimEmail2);

                Claim claimFoto = new Claim("Foto", usuario.Foto.ToString());
                identity.AddClaim(claimFoto);

                ClaimsPrincipal userPrincipal = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync(
                    CookieAuthenticationDefaults.AuthenticationScheme,
                    userPrincipal);

                string controller = TempData["controller"].ToString();
                string action = TempData["action"].ToString();

                if (TempData["id"] != null)
                {
                    string id = "";
                    id = TempData["id"].ToString();
                    return RedirectToAction(action, controller, new { id = id });
                }
                else
                {
                    return RedirectToAction(action, controller);
                }
            }
            else
            {
                ViewData["MENSAJE"] = "Usuario/Password incorrectos";
                return View();
            }
        }

        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync
                (CookieAuthenticationDefaults.AuthenticationScheme);

            return RedirectToAction("Index", "Libros");
        }

        public IActionResult AccesoDenegado()
        {
            return View();
        }

    }
}

ViewComponents/MenuGenerosViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using PruebaExamen.Repositories;
using SegundaPracticaMVC.Filters;
using SegundaPracticaMVC.Models;
using SegundaPracticaMVC.Repositories;

namespace SegundaPracticaMVC.ViewComponents
{
    public class MenuGenerosViewComponent : ViewComponent
    {
        private RepositoryLibros repo;

        public MenuGenerosViewComponent(RepositoryLibros repo)
        {
            this.repo = repo;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<Genero> generos = await this.repo.GetAllGenerosAsync();
            return View(generos);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SegundaPracticaMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SegundaPracticaMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SegundaPracticaMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Libros" asp-action="Index">Libros</a>
                        </li>
                        @await Component.InvokeAsync("MenuGeneros")
                        <partial name="_MenuUsuarios" />



                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SegundaPracticaMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_MenuUsuarios.cshtml
@using System.Security.Claims;
@{
    var cantidadCarrito = Context.Session.GetObject<int>("CANTIDADCARRITO");

    var usernameClaim = User.FindFirst("Foto");
    var fotoUser = usernameClaim?.Value;
}


@if (Context.User.Identity.IsAuthenticated == false)
{
    <li class="nav-item">
        <a asp-controller="Libros"
            asp-action="PerfilUsuario"
            class="nav-link">
            Log In
        </a>
    </li>
}
else
{
    <li class="nav-item">
        <a asp-controller="Managed"
            asp-action="Logout"
            class="nav-link">
            Log out <span style="color:blue">
            </span>
        </a>
    </li>
    <li class="nav-item">
        <a asp-controller="Libros"
           asp-action="PerfilUsuario"
           class="nav-link">
            @Context.User.Identity.Name
            <span>
                <img src="@HelperPathProvider.MapUrlPath(fotoUser ,Folders.Usuarios)" style="height:50px; width:50px" />
            </span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link"
           asp-controller="Libros"
           asp-action="Carrito">
            Carrito: @cantidadCarrito
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link"
           asp-controller="Libros"
           asp-action="PedidosUsuario"
           asp-route-id="@Context.User.FindFirst("id").Value">
            Pedidos
        </a>
    </li>


}