Models/Libro.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace SegundaPracticaMVC.Models
{
    [Table("LIBROS")]
    public class Libro
    {
        [Key]
        [Column("IdLibro")]
        public int IdLibro { get; set; }

        [Column("Titulo")]
        public string Titulo { get; set; }

        [Column("Autor")]
        public string Autor { get; set; }

        [Column("Editorial")]
        public string Editorial { get; set; }

        [Column("Portada")]
        public string Portada { get; set; }

        [Column("Resumen")]
        public string Resumen { get; set; }

        [Column("Precio")]
        public int Precio { get; set; }
        [Column("IdGenero")]
        public int IdGenero { get; set; }

    }
}

Controllers/LibrosController.cs
using Microsoft.AspNetCore.Mvc;
using SegundaPracticaMVC.Repositories;
using SegundaPracticaMVC.Filters;
using PruebaExamen.Repositories;
using SegundaPracticaMVC.Models;
using SegundaPracticaMVC.Extensions;

namespace SegundaPracticaMVC.Controllers
{
    public class LibrosController : Controller
    {
        private RepositoryLibros repo;
        public LibrosController(RepositoryLibros repo)
        {
            this.repo = repo;
        }

        [AuthorizeUsuarios]
        public IActionResult PerfilUsuario()
        {
            return View();
        }
        [AuthorizeUsuarios]
        public async Task<IActionResult> Index()
        {
            List<Libro> libros = await this.repo.GetLibrosAsync();
            return View(libros);
        }


        [AuthorizeUsuarios]
        public async Task<IActionResult> LibrosGenero(int idgenero)
        {
            List<Libro> peliculasGenero = await this.repo.LibrosGeneroAsync(idgenero);
            return View(peliculasGenero);
        }

        [AuthorizeUsuarios]
        public async Task<IActionResult> DetallesLibro(int id)
        {
            Libro libro = await this.repo.FindLibroAsync(id);
            return View(libro);
        }
        public IActionResult GuardarLibroCarrito(int idLibro)
        {
            int cantidadCarrito = HttpContext.Session.GetObject<int>("CANTIDADCARRITO");
            if (idLibro != null)
            {
                List<int> carrito;
                if (HttpContext.Session.GetObject<List<int>>("CARRITO") == null)
                {
                    carrito = new List<int>();
                }
                else
                {
                    carrito = HttpContext.Session.GetObject<List<int>>("CARRITO");
                }
                carrito.Add(idLibro);
                HttpContext.Session.SetObject("CARRITO", carrito);
                HttpContext.Session.SetObject("CANTIDADCARRITO", carrito.Count);
            }

                return RedirectToAction("DetallesLibro", new { id = idLibro });

        }

        public IActionResult Carrito(int? idLibroEliminar)
        {
            //LE PASAMOS EL CARRITO
            List<int> carrito = HttpContext.Session.GetObject<List<int>>("CARRITO");
            int cantidadCarrito = carrito.Count;
            //TIENES QUE CREAR PARA AÑADIR DATOS AL CARRITO
            if (carrito == null)
            {
                return View();
            }
            else
            {
                if (idLibroEliminar != null)
                {
                    carrito.Remove(idLibroEliminar.Value);
                    cantidadCarrito--;
                    HttpContext.Session.SetObject("CARRITO", carrito);
                    HttpContext.Session.SetObject("CANTIDADCARRITO", cantidadCarrito);
                }
                List<Libro> libros = this.repo.GetLibrosCarrito(carrito);
                return View(libros);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Comprar(List<int> libros, int iduser)
        {
            int idpedido = await repo.GetUltimoPedido();
            int idfactura = await repo.GetUltimaFactura()+1;
            for (int i = 0; i < libros.Count; i++)
            {
                int libro = libros[i];

                idpedido++;
                Pedido nuevoPedido = new Pedido()
                {
                    IdPedido = idpedido,
                    IdFactura = idfactura,
                    IdLibro = libro,
                    FechaCompra = DateTime.Now,
                    IdUsuario = iduser,
                    Cantidad = 1
                };

                await repo.Comprar(nuevoPedido);

            }
            HttpContext.Session.Remove("CARRITO");
            HttpContext.Session.Remove("CANTIDADCARRITO");

            return RedirectToAction("Index");
        }


        [AuthorizeUsuarios]
        public async Task<IActionResult> PedidosUsuario(int id)
        {
            List<ViewPedidos> pedidos = await this.repo.GetPedidosUsuario(id);
            return View(pedidos);
        }



    }
}

Views/Libros/Carrito.cshtml
@model IEnumerable<SegundaPracticaMVC.Models.Libro>

@{
    ViewData["Title"] = "Carrito";
}

<h1>Carrito de Compras</h1>

@if (Model != null && Model.Any())
{
    <form asp-controller="Libros" asp-action="Comprar" method="post">
        @for (int i = 0; i < Model.Count(); i++)
        {
            <input type="hidden" name="libros[@i]" value="@Model.ElementAt(i).IdLibro" />
            <input type="hidden" name="iduser" value="@Context.User.FindFirst("id").Value" />
        }

        <table class="table">
            <thead>
                <tr>
                    <th class="text-center">Portada</th>
                    <th class="text-center">Título</th>
                    <th class="text-center">Autor</th>
                    <th class="text-center">Editorial</th>
                    <th class="text-center">Precio</th>
                    <th class="text-center">Acciones</th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < Model.Count(); i++)
                {
                    <tr>
                        <td class="align-middle text-center"><img src="@HelperPathProvider.MapUrlPath(Model.ElementAt(i).Portada, Folders.Libros)" style="height:100px; width:70px" /></td>
                        <td class="align-middle text-center">@Html.DisplayFor(_ => Model.ElementAt(i).Titulo)</td>
                        <td class="align-middle text-center">@Html.DisplayFor(_ => Model.ElementAt(i).Autor)</td>
                        <td class="align-middle text-center">@Html.DisplayFor(_ => Model.ElementAt(i).Editorial)</td>
                        <td class="align-middle text-center">@Html.DisplayFor(_ => Model.ElementAt(i).Precio)</td>
                        <td class="align-middle text-center">
                            <a asp-controller="Libros" asp-action="Carrito" asp-route-idLibroEliminar="@Model.ElementAt(i).IdLibro" class="btn btn-outline-danger">
                                Eliminar
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>


        <button type="submit" class="btn btn-primary">Finalizar Compra</button>
    </form>
}
else
{
    <div class="alert alert-info" role="alert">
        Tu carrito está vacío.
    </div>
}

Views/Libros/DetallesLibro.cshtml
@model Libro

@{
    ViewData["Title"] = "Detalles del Libro";
    List<int> carrito = Context.Session.GetObject<List<int>>("CARRITO");
}

<div class="row">
    <div class="col-md-4 mb-4">
        <div class="card">
            <div class="card-body">
                <img src="@HelperPathProvider.MapUrlPath(Model.Portada, Folders.Libros)" width="100px" />
                <h5 class="card-title">@Model.Titulo</h5>
                <p class="card-text">Autor: @Model.Autor</p>
                <p class="card-text">Editorial: @Model.Editorial</p>
                <p class="card-text">Resumen: @Model.Resumen</p>
                <p class="card-text">Precio: @Model.Precio</p>
                <a asp-controller="Libros"
                   asp-action="Index"
                   class="btn btn-info">
                    Volver al Inicio
                </a>
                @if (carrito != null && carrito.Contains(Model.IdLibro))
                {
                    <button class="btn btn-outline-success" disabled>
                        Añadido al Carrito
                    </button>
                }
                else
                {
                    <a asp-controller="Libros"
                       asp-action="GuardarLibroCarrito"
                       asp-route-idLibro="@Model.IdLibro"
                       class="btn btn-info">
                        Comprar
                    </a>
                }
            </div>
        </div>
    </div>
</div>

Views/Libros/Index.cshtml
@model List<Libro>

@{
    ViewData["Title"] = "Index";
    List<int> carrito = Context.Session.GetObject<List<int>>("CARRITO");
}


<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4 mb-4">
            <div class="card">
                <div class="card-body">
                    <img src="@HelperPathProvider.MapUrlPath(@item.Portada ,Folders.Libros)" style="height:430px; width:100%" />
                    <h5 class="card-title">@item.Titulo</h5>
                    <a asp-controller="Libros"
                       asp-action="DetallesLibro"
                       asp-route-id="@item.IdLibro"
                       class="btn btn-info">
                        Detalles
                    </a>
                </div>
            </div>
        </div>
    }
</div>

Views/Libros/LibrosGenero.cshtml
@model List<Libro>

@{
    ViewData["Title"] = "Index";
    List<int> carrito = Context.Session.GetObject<List<int>>("CARRITO");
}


<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4 mb-4">
            <div class="card">
                <div class="card-body">
                    <img src="@HelperPathProvider.MapUrlPath(@item.Portada ,Folders.Libros)" style="height:430px; width:100%" />
                    <h5 class="card-title">@item.Titulo</h5>
                    <a asp-controller="Libros"
                       asp-action="DetallesLibro"
                       asp-route-id="@item.IdLibro"
                       class="btn btn-info">
                        Detailles
                    </a>

                </div>
            </div>
        </div>
    }
</div>

Views/Libros/PedidosUsuario.cshtml
@model List<SegundaPracticaMVC.Models.ViewPedidos>

<h1>Pedidos del Usuario</h1>

<table class="table">
    <thead>
        <tr>
            <th>ID Pedido</th>
            <th>Nombre</th>
            <th>Apellidos</th>
            <th>Título del Libro</th>
            <th>Precio</th>
            <th>Portada</th>
            <th>Fecha de Compra</th>
            <th>Precio Final</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var pedido in Model)
        {
            <tr>
                <td>@pedido.IdVistaPedido</td>
                <td>@pedido.Nombre</td>
                <td>@pedido.Apellidos</td>
                <td>@pedido.Titulo</td>
                <td>@pedido.Precio</td>
                <td>
                    <img src="@HelperPathProvider.MapUrlPath(pedido.Portada ,Folders.Libros)" style="height:100px; width:70px" />
                </td>
                <td>@pedido.Fecha.ToString("dd/MM/yyyy")</td>
                <td>@pedido.PrecioFinal</td>
            </tr>
        }
    </tbody>
</table>

Views/Libros/PerfilUsuario.cshtml
@using System.Security.Claims

<h1>
    Nombre: @Context.User.Identity.Name
</h1>

<ul class="list-group">
    <li class="list-group-item">
        @Context.User.FindFirst("Email").ToString()
    </li>
    <li class="list-group-item">
        Id: @Context.User.FindFirst("id").Value
    </li>
</ul>